# Generated by Django 5.0.3 on 2024-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('clg_name', models.CharField(choices=[('skasc', 'SKASC'), ('hindustan', 'Hindustan')], max_length=50)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
